
CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'P@ssw0rd@123';


CREATE DATABASE SCOPED CREDENTIAL AzureStorageCredential
WITH
  IDENTITY = 'devrajclass2',
  SECRET = '5+Z5pgRQSdDl9gJVkstZ3dBRKKPL3MSqAPBVOFdeXCYt7yGnRBa0o0xH3KUdCj1wuThfW5zppBZxi3syC9dHiQ==';
  
  
